### ISSUE TITLE
RuntimeError: Spawn failed because of collision at spawn position

### ISSUE THREAD

**Issue by asevenster** [tud-hri/joan#2] opened 2021-06-10 07:04 UTC
When the following error occurs 
**RuntimeError: Spawn failed because of collision at spawn position**
 JOAN freezes and you have to restart the program and your experiment. 
![image](https://user-images.githubusercontent.com/80531925/121479910-ce7ff080-c9ca-11eb-9a8a-e66f92661b53.png)

**Comment by OlgerSiebinga** [comment] 2021-07-01 11:07
This seems to be a generic problem with all JOAN modules. If an exception occurs in the get_ready() function of a module, the except_hook is called but the process is not terminated correctly. But I'm not sure what exactly is happening.

**Comment by niekbeckers** [comment] 2021-07-01 11:51
On top of Olger's answer - the origin of the problem is that CARLA tries to
spawn a car on top of another already existing car. The existing car is
there because a) CARLA hasn't disposed of it properly, b) JOAN hasn't
disposed of the car properly (e.g. due to a crash of JOAN).

One approach is to check what cars are already spawned in CARLA before
spawning new cars to avoid this issue.

**Comment by OlgerSiebinga** [comment] 2021-07-29 13:02
Turns out the module manager got stuck in an infinite loop because it was waiting for the `get_ready()` function to trigger the `module_is_ready` event. The excepthook exited the process before this event was set, causing the module manager to hang. This issue was fixed in commit a99a02238ae879a7cb4c89bdddb8e7a329de5996 by setting the event from the excepthook before exiting.

**Closed by OlgerSiebinga** 2021-07-29 13:02 UTC
Labels: bug
